-- AlterTable
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "birthYear" INTEGER;
